modules_to_check:
  - name: "SpiffWorkflow"
    description: "Core workflow engine"
    import_path: "SpiffWorkflow"
    version_attr: "__version__"
    
  - name: "BPMN workflows"
    description: "Business Process Model and Notation 2.0"
    import_path: "SpiffWorkflow.bpmn"
    test_imports:
      - "SpiffWorkflow.bpmn.workflow"
      - "SpiffWorkflow.bpmn.parser.BpmnParser"
    test_instantiation: "SpiffWorkflow.bpmn.parser.BpmnParser.BpmnParser"
    
  - name: "DMN decisions"
    description: "Decision Model and Notation"
    import_path: "SpiffWorkflow.dmn"
    test_imports:
      - "SpiffWorkflow.dmn.parser.BpmnDmnParser"
    test_instantiation: "SpiffWorkflow.dmn.parser.BpmnDmnParser.BpmnDmnParser"
    
  - name: "Python script tasks"
    description: "Custom Python execution in workflows"
    import_path: "SpiffWorkflow.bpmn.specs"
    test_imports:
      - "SpiffWorkflow.bpmn.specs.bpmn_task_spec"
    test_classes:
      - "SpiffWorkflow.bpmn.specs.bpmn_task_spec.BpmnTaskSpec"

  - name: "LinkML"
    description: "Schema modeling and validation framework"
    import_path: "linkml"
    version_attr: "__version__"
    
  - name: "LinkML runtime"
    description: "Runtime schema processing and validation"
    import_path: "linkml_runtime"
    test_imports:
      - "linkml_runtime.loaders"
      - "linkml_runtime.dumpers"
      - "linkml_runtime.utils.schemaview"
    test_classes:
      - "linkml_runtime.utils.schemaview.SchemaView"
    
  - name: "LinkML generators"
    description: "Code generation from LinkML schemas"
    import_path: "linkml.generators"
    test_imports:
      - "linkml.generators.pydanticgen"
      - "linkml.generators.jsonldgen"
      - "linkml.generators.pythongen"
    test_classes:
      - "linkml.generators.pydanticgen.PydanticGenerator"
      
  - name: "LinkML validation"
    description: "Schema validation and constraint checking"
    import_path: "linkml_runtime.linkml_model"
    test_imports:
      - "linkml_runtime.linkml_model.meta"
    test_classes:
      - "linkml_runtime.linkml_model.meta.SchemaDefinition"

messages:
  success: "✅ {name} available"
  error: "❌ {name} failed: {error}"
  not_found: "❌ {name} not installed"
  install_hint: "   Install: pip install SpiffWorkflow"
  
output:
  header: "🔍 REAL SPIFF VERIFICATION"
  separator: "=" 
  separator_length: 35
