
CC = gcc
CFLAGS = -O3 -march=native -I./include
LDFLAGS =

SRC = src/bitactor_80_20.c src/bitactor_ttl_compiler.c bitactor_80_20_main.c
OBJ = $(SRC:.c=.o)

TARGET = bitactor_80_20_demo

.PHONY: all clean

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -f $(OBJ) $(TARGET)
