# AutoTel Configuration File
# This file can be used to configure DSPy models and other settings

# Global DSPy Configuration
dspy:
  # Default model for all signatures (can be overridden per signature)
  default_model: "ollama/qwen2.5:latest"
  default_temperature: 0.7
  default_max_tokens: 1000
  
  # Model-specific configurations
  models:
    qwen2.5:
      provider: "ollama"
      model: "qwen2.5:latest"
      temperature: 0.7
      max_tokens: 1000
      timeout: 30
    
    gpt4:
      provider: "openai"
      model: "gpt-4"
      temperature: 0.3
      max_tokens: 2000
      timeout: 60
    
    claude:
      provider: "anthropic"
      model: "claude-3-sonnet-20240229"
      temperature: 0.5
      max_tokens: 1500
      timeout: 45

# Signature-specific overrides
signatures:
  CustomerFeedbackAnalyzer:
    model: "qwen2.5"
    temperature: 0.8  # Higher temperature for more creative analysis
    max_tokens: 1500
  
  SentimentAnalyzer:
    model: "gpt4"
    temperature: 0.3  # Lower temperature for more consistent sentiment analysis

# Workflow Configuration
workflow:
  validation:
    strict: true
    check_signatures: true
    check_dmn: true
  
  execution:
    timeout: 300  # 5 minutes
    retry_attempts: 3
    save_intermediate_results: true

# Logging Configuration
logging:
  level: "INFO"
  format: "json"
  include_timestamps: true
  include_workflow_id: true

# Output Configuration
output:
  format: "json"
  include_debug: false
  include_execution_time: true
  include_model_usage: true 