// AUTO-GENERATED by the CNS OWL AOT compiler
#ifndef ONTOLOGY_IDS_H
#define ONTOLOGY_IDS_H

// ============================================================================
// CNS OWL AOT - ENTITY ID MAPPINGS
// ============================================================================
// This file provides ahead-of-time compiled entity IDs for maximum performance
// 7T compliance: All lookups are O(1) constant time operations

// Core RDF/OWL vocabulary
#define ID_rdf_type                1
#define ID_rdfs_subClassOf         2
#define ID_rdfs_domain             3
#define ID_rdfs_range              4
#define ID_owl_equivalentClass     5
#define ID_owl_disjointWith        6
#define ID_owl_sameAs              7
#define ID_owl_differentFrom       8
#define ID_owl_inverseOf           9
#define ID_owl_TransitiveProperty  10
#define ID_owl_SymmetricProperty   11
#define ID_owl_FunctionalProperty  12
#define ID_owl_InverseFunctionalProperty 13

// Example domain classes (Employee ontology from OWL-AOT.md)
#define ID_Employee                1001
#define ID_Manager                 1002
#define ID_IndividualContributor   1003
#define ID_Contractor              1004
#define ID_Person                  1005
#define ID_Human                   1006
#define ID_Animal                  1010
#define ID_Mammal                  1011
#define ID_Dog                     1012

// Example domain properties
#define ID_worksAt                 2001
#define ID_manages                 2002
#define ID_isManagedBy             2003
#define ID_hasStatus               2004
#define ID_hasName                 2005
#define ID_knows                   2006
#define ID_worksWith               2007
#define ID_ancestor                2008
#define ID_reports_to_transitively 2009

// Test entities for benchmarks
#define ID_TestClass_1             3001
#define ID_TestClass_2             3002
#define ID_TestClass_3             3003
#define ID_TestClass_4             3004
#define ID_TestClass_5             3005
#define ID_TestProperty_1          4001
#define ID_TestProperty_2          4002
#define ID_TestProperty_3          4003

// Entity count constants for array sizing
#define CNS_OWL_MAX_CLASSES        64
#define CNS_OWL_MAX_PROPERTIES     64
#define CNS_OWL_MAX_INDIVIDUALS    64

// SPARQL AOT additions
#define RDF_TYPE ID_rdf_type
#define RDFS_LABEL 100
#define FOAF_NAME ID_hasName
#define FOAF_KNOWS ID_knows
#define FOAF_EMAIL 101
#define DC_TITLE 102
#define DC_CREATOR 103
#define PERSON_CLASS ID_Person
#define DOCUMENT_CLASS 104
#define ORGANIZATION_CLASS 105
#define CUSTOMER_CLASS 106
#define HAS_NAME ID_hasName
#define HAS_EMAIL FOAF_EMAIL
#define LIFETIME_VALUE 107
#define MEMBER_OF 108
#define S7T_SQL_MAX_ROWS 1000

// Utility macros for ID validation
#define CNS_OWL_IS_VALID_CLASS_ID(id)     ((id) >= 1000 && (id) < 2000)
#define CNS_OWL_IS_VALID_PROPERTY_ID(id)  ((id) >= 2000 && (id) < 3000)
#define CNS_OWL_IS_VALID_TEST_ID(id)      ((id) >= 3000 && (id) < 5000)

#endif // ONTOLOGY_IDS_H